# Generated by Django 6.1.1 on 2026-09-14 12:13

import django.db.models.deletion
import django.utils.timezone
import lostfound.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=lostfound.models.generate_lf_ref, editable=False, max_length=30, unique=True)),
                ('title', models.CharField(help_text='Short title e.g. Silver iPhone 15 Pro, Black Montblanc Wallet', max_length=150)),
                ('category', models.CharField(choices=[('electronics', 'Electronics (Phones, Laptops, Earbuds, Chargers, Cameras)'), ('wallet_cash', 'Wallets, Purses & Cash'), ('jewelry', 'Jewelry, Watches & Luxury Goods'), ('documents', 'Passports, IDs, Bank Cards & Keys'), ('luggage_bags', 'Baggage, Backpacks & Briefcases'), ('clothing', 'Clothing, Eyewear & Shoes'), ('accessories', 'Hats, Umbrellas, Personal Items'), ('other', 'Other Miscellaneous Items')], default='electronics', max_length=30)),
                ('value_tier', models.CharField(choices=[('normal', 'Standard Item'), ('high_value', 'High Value (Safe Custody Required)'), ('sensitive', 'Confidential / Sensitive Documents / Cash')], default='normal', max_length=20)),
                ('description', models.TextField(help_text='Detailed physical description, condition, distinguishing marks, scratches, lock-screen wallpaper, serial numbers')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, help_text='IMEI, serial number, or card ending digits', max_length=100)),
                ('found_location', models.CharField(help_text='e.g. Main Lobby Couch, Room 412, Restaurant Table 8, Gym', max_length=150)),
                ('found_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finder_name', models.CharField(blank=True, max_length=100)),
                ('finder_type', models.CharField(choices=[('staff', 'Hotel Staff Member'), ('guest', 'Hotel Guest / Visitor'), ('security', 'Security Officer / Patrol'), ('contractor', 'Contractor / Vendor')], default='staff', max_length=30)),
                ('finder_phone', models.CharField(blank=True, max_length=30)),
                ('storage_location', models.CharField(default='Security Main Safe', help_text='e.g. Safe Box A, Locker #14, Shelf 2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed (In Custody)'), ('investigating', 'Claim In Verification'), ('claimed', 'Claimed & Returned'), ('disposed', 'Disposed / Discarded'), ('donated', 'Donated to Charity'), ('police', 'Transferred to Police / Authorities')], default='unclaimed', max_length=20)),
                ('primary_photo', models.ImageField(blank=True, null=True, upload_to='lostfound_photos/')),
                ('claimant_name', models.CharField(blank=True, max_length=150)),
                ('claimant_phone', models.CharField(blank=True, max_length=30)),
                ('claimant_id_number', models.CharField(blank=True, max_length=50)),
                ('proof_of_ownership', models.TextField(blank=True, help_text='How claimant proved ownership: passcode entry, receipt, invoice, hidden mark')),
                ('handover_date', models.DateTimeField(blank=True, null=True)),
                ('claimant_signature_photo', models.ImageField(blank=True, null=True, upload_to='claim_signatures/')),
                ('handover_notes', models.TextField(blank=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_logged', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='lostfound_photos/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lostfound.lostfounditem')),
            ],
        ),
    ]
