# Generated by Django 6.1.1 on 2026-09-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Gate 1 - Loading Dock', max_length=100)),
                ('name_ar', models.CharField(blank=True, help_text='e.g. بوابة 1 - رصيف التحميل', max_length=100)),
                ('code', models.CharField(help_text='e.g. GATE-01', max_length=30, unique=True)),
                ('gate_type', models.CharField(choices=[('service', 'Loading Dock & Service / رصيف التحميل والخدمات'), ('main', 'Main Gate & Barrier / البوابة الرئيسية والحاجز الأمني'), ('staff', 'Staff & Contractor Entrance / مدخل الموظفين والمقاولين'), ('basement', 'Basement Ramp & Parking / قبو الخدمات والمواقف'), ('vip', 'VIP / Protocol Gate / بوابة كبار الشخصيات والبروتوكول')], default='service', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='action',
            field=models.CharField(choices=[('CHECK_IN', 'Visitor Checked In'), ('CHECK_OUT', 'Visitor Checked Out'), ('VISITOR_DENIED', 'Visitor Entry Denied'), ('LF_LOGGED', 'Lost & Found Item Logged'), ('LF_CLAIMED', 'Lost & Found Item Handed Over'), ('LF_DISPOSED', 'Lost & Found Item Disposed'), ('SECURITY_ALERT', 'Security Incident Flagged'), ('GATE_ADDED', 'New Security Gate Created')], max_length=30),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.securitygate'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_officers', to='core.securitygate'),
        ),
    ]
