# Generated by Django 6.1.1 on 2026-09-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_securitygate_alter_securityauditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditlog',
            name='action',
            field=models.CharField(choices=[('CHECK_IN', 'Visitor Checked In'), ('CHECK_OUT', 'Visitor Checked Out'), ('VISITOR_DENIED', 'Visitor Entry Denied'), ('LF_LOGGED', 'Lost & Found Item Logged'), ('LF_CLAIMED', 'Lost & Found Item Handed Over'), ('LF_DISPOSED', 'Lost & Found Item Disposed'), ('SECURITY_ALERT', 'Security Incident Flagged'), ('PASS_CREATED', 'Gate Pass Issued / Dispatched'), ('PASS_EDITED', 'Gate Pass Modified / Updated'), ('PASS_DELETED', 'Gate Pass Deleted / Cancelled'), ('GATE_ADDED', 'New Security Gate Created'), ('GATE_EDITED', 'Security Gate Modified'), ('GATE_DELETED', 'Security Gate Deactivated / Deleted')], max_length=30),
        ),
    ]
