# Generated by Django 6.1.1 on 2026-09-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_securityauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Riyadh Grand Palace Hotel', max_length=150)),
                ('name_ar', models.CharField(blank=True, help_text='e.g. فندق قصر الرياض الكبير', max_length=150)),
                ('code', models.CharField(help_text='e.g. PROP-RUH-01', max_length=30, unique=True)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel & Luxury Resort / فندق ومنتجع سياحي'), ('commercial', 'Commercial Tower & Business Hub / برج تجاري ومجمع أعمال'), ('logistics', 'Logistics & Industrial Park / مجمع لوجستي ومستودعات'), ('residential', 'Residential Compound / مجمع سكني خاص'), ('healthcare', 'Hospital & Medical City / مستشفى ومدينة طبية'), ('campus', 'Educational / University Campus / حرم جامعي أو تعليمي'), ('mixed_use', 'Mixed-Use Development / مشروع متعدد الاستخدامات')], default='hotel', max_length=20)),
                ('city', models.CharField(default='Riyadh', max_length=100)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('manager_name', models.CharField(blank=True, help_text='General Manager or Security Director', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='action',
            field=models.CharField(choices=[('CHECK_IN', 'Visitor Checked In'), ('CHECK_OUT', 'Visitor Checked Out'), ('VISITOR_DENIED', 'Visitor Entry Denied'), ('LF_LOGGED', 'Lost & Found Item Logged'), ('LF_CLAIMED', 'Lost & Found Item Handed Over'), ('LF_DISPOSED', 'Lost & Found Item Disposed'), ('SECURITY_ALERT', 'Security Incident Flagged'), ('PASS_CREATED', 'Gate Pass Issued / Dispatched'), ('PASS_EDITED', 'Gate Pass Modified / Updated'), ('PASS_DELETED', 'Gate Pass Deleted / Cancelled'), ('GATE_ADDED', 'New Security Gate Created'), ('GATE_EDITED', 'Security Gate Modified'), ('GATE_DELETED', 'Security Gate Deactivated / Deleted'), ('PROPERTY_CREATED', 'New Property Added'), ('PROPERTY_EDITED', 'Property Details Updated'), ('PROPERTY_DEACTIVATED', 'Property Deactivated'), ('USER_CREATED', 'Security User Created'), ('USER_EDITED', 'Security User Updated')], max_length=30),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.property'),
        ),
        migrations.AddField(
            model_name='securitygate',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='core.property'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='core.property'),
        ),
    ]
