# Generated by Django 6.1.1 on 2026-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_alter_securityauditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cluster_properties',
            field=models.ManyToManyField(blank=True, help_text='Cluster properties managed by this Director / Admin (e.g. Property 1, 2, 3, 4)', related_name='cluster_directors', to='core.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Chief of Security / Director'), ('cluster_director', 'Cluster Security Director / مدير أمن القطاع'), ('supervisor', 'Shift Supervisor'), ('officer', 'Security Officer / Gate Guard'), ('front_desk', 'Front Desk / Concierge'), ('auditor', 'Safety & Auditor')], default='officer', max_length=25),
        ),
    ]
