# Generated by Django 6.1.1 on 2026-09-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_cluster_properties_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly / شهري'), ('quarterly', 'Quarterly / ربع سنوي'), ('annually', 'Annually / سنوي')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='buyer_company',
            field=models.CharField(blank=True, help_text='Client Organization / Company Name', max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='buyer_name',
            field=models.CharField(blank=True, help_text='Buyer / Primary Contact Person', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=1500.0, help_text='Monthly SaaS subscription fee in SAR', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plan_tier',
            field=models.CharField(choices=[('starter', 'Starter Package / الباقة الأساسية (500 SAR/mo)'), ('professional', 'Professional Facility / باقة المنشآت الاحترافية (1,500 SAR/mo)'), ('enterprise', 'Enterprise Cluster / باقة المؤسسات والقطاعات (3,500 SAR/mo)')], default='professional', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='subscription_notes',
            field=models.TextField(blank=True, help_text='Contract notes, discounts, terms'),
        ),
        migrations.AddField(
            model_name='property',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active & Paid / نشط ومسدد'), ('trial', 'Free Trial / تجريبي'), ('past_due', 'Payment Due / متأخر السداد'), ('suspended', 'Suspended / موقوف لعدم السداد'), ('cancelled', 'Cancelled / ملغي')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='action',
            field=models.CharField(choices=[('CHECK_IN', 'Visitor Checked In'), ('CHECK_OUT', 'Visitor Checked Out'), ('VISITOR_DENIED', 'Visitor Entry Denied'), ('LF_LOGGED', 'Lost & Found Item Logged'), ('LF_CLAIMED', 'Lost & Found Item Handed Over'), ('LF_DISPOSED', 'Lost & Found Item Disposed'), ('SECURITY_ALERT', 'Security Incident Flagged'), ('PASS_CREATED', 'Gate Pass Issued / Dispatched'), ('PASS_EDITED', 'Gate Pass Modified / Updated'), ('PASS_DELETED', 'Gate Pass Deleted / Cancelled'), ('GATE_ADDED', 'New Security Gate Created'), ('GATE_EDITED', 'Security Gate Modified'), ('GATE_DELETED', 'Security Gate Deactivated / Deleted'), ('PROPERTY_CREATED', 'New Property Added'), ('PROPERTY_EDITED', 'Property Details Updated'), ('PROPERTY_DEACTIVATED', 'Property Deactivated'), ('USER_CREATED', 'Security User Created'), ('USER_EDITED', 'Security User Updated'), ('CLIENT_ONBOARDED', 'New Client Property Onboarded'), ('FEE_COLLECTED', 'Monthly Subscription Fee Collected'), ('SUBSCRIPTION_SUSPENDED', 'Client Property Suspended'), ('SUBSCRIPTION_REACTIVATED', 'Client Property Reactivated'), ('INVOICE_GENERATED', 'Monthly Invoice Generated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('saas_owner', 'SaaS Platform Owner & Vendor / بائع ومطور النظام'), ('director', 'Chief of Security / Director'), ('cluster_director', 'Cluster Security Director / مدير أمن القطاع'), ('supervisor', 'Shift Supervisor'), ('officer', 'Security Officer / Gate Guard'), ('front_desk', 'Front Desk / Concierge'), ('auditor', 'Safety & Auditor')], default='officer', max_length=25),
        ),
        migrations.CreateModel(
            name='PropertySubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='e.g. INV-202609-RUH01', max_length=50, unique=True)),
                ('billing_period', models.CharField(help_text='e.g. September 2026', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid / تم التحصيل'), ('unpaid', 'Unpaid / معلق'), ('overdue', 'Overdue / متأخر')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer / تحويل بنكي'), ('mada', 'Mada / مدى'), ('credit_card', 'Credit Card / بطاقة ائتمان'), ('cheque', 'Cheque / شيك مصدّق'), ('cash', 'Cash / نقداً')], max_length=30)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank Ref / Receipt Number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
