# Generated by Django 6.1.1 on 2026-09-14 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('GREEN', '🟢 Green Card — Returnable Material Pass (MUST RETURN)'), ('RED', '🔴 Red Card — Non-Returnable Material Pass (PERMANENT OUT)')], default='GREEN', max_length=10)),
                ('pass_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('physical_card_ref', models.CharField(blank=True, help_text='Optional physical plastic card / badge number (e.g. Card #12)', max_length=50)),
                ('sender_name', models.CharField(help_text='Department staff member dispatching the items', max_length=120)),
                ('sender_email', models.EmailField(blank=True, help_text='Email for departure receipt and return notifications', max_length=254)),
                ('sender_phone', models.CharField(blank=True, help_text='Department phone / WhatsApp', max_length=30)),
                ('destination_entity', models.CharField(help_text='Company, workshop, vendor, or recipient facility', max_length=150)),
                ('destination_address', models.CharField(blank=True, max_length=200)),
                ('destination_contact_name', models.CharField(blank=True, max_length=120)),
                ('destination_phone', models.CharField(blank=True, max_length=30)),
                ('destination_email', models.EmailField(blank=True, max_length=254)),
                ('carrier_name', models.CharField(help_text='Driver or employee physically transporting the items', max_length=120)),
                ('carrier_phone', models.CharField(help_text='Mobile number for WhatsApp reminders', max_length=30)),
                ('carrier_id_number', models.CharField(blank=True, help_text='National ID / Iqama / License', max_length=50)),
                ('carrier_company', models.CharField(blank=True, help_text='Transport company or logistics service', max_length=120)),
                ('vehicle_plate', models.CharField(blank=True, help_text='e.g. KSA 4921 RKD', max_length=30)),
                ('vehicle_model', models.CharField(blank=True, help_text='e.g. White Isuzu Truck', max_length=60)),
                ('purpose', models.CharField(choices=[('repair', 'External Repair & Servicing'), ('calibration', 'Calibration & Testing'), ('warranty', 'Warranty Replacement / Vendor Return'), ('inter_branch', 'Inter-Branch / Sister Hotel Transfer'), ('demo', 'Exhibition / Demonstration / Event Loan'), ('scrap', 'Scrap Disposal / Recycling Waste'), ('donation_sale', 'Sold Surplus / Donated Asset'), ('guest_property', 'Guest Property Dispatched / Courier'), ('other', 'Other Authorized Purpose')], default='repair', max_length=30)),
                ('purpose_notes', models.TextField(blank=True, help_text='Detailed justification of movement')),
                ('authorized_by_manager', models.CharField(help_text='Department Head or Director who signed approval', max_length=120)),
                ('approval_document_photo', models.ImageField(blank=True, null=True, upload_to='gatepass_approvals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gate_location', models.CharField(default='Loading Dock Gate', max_length=50)),
                ('exit_cargo_photo', models.ImageField(blank=True, null=True, upload_to='gatepass_cargo_exit/')),
                ('expected_return_date', models.DateTimeField(blank=True, help_text='Mandatory return cutoff for Green Cards', null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('return_cargo_photo', models.ImageField(blank=True, null=True, upload_to='gatepass_cargo_return/')),
                ('status', models.CharField(choices=[('active', 'Out In-Transit'), ('overdue', 'Overdue for Return'), ('partially_returned', 'Partially Returned'), ('fully_returned', 'Fully Returned & Closed'), ('dispatched_closed', 'Dispatched & Closed (Permanent Out)'), ('cancelled', 'Cancelled')], default='active', max_length=25)),
                ('security_notes', models.TextField(blank=True)),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_dispatched', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes_sent', to='visitors.departmenthost')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g. Chiller Water Pump, Dining Chairs, Drill Press', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='pcs', help_text='pcs, sets, boxes, kg, meters', max_length=30)),
                ('serial_asset_tag', models.CharField(blank=True, help_text='Serial number or asset tag e.g. ASSET-ENG-4910', max_length=100)),
                ('condition_out', models.CharField(choices=[('good', 'Good Working Condition'), ('for_repair', 'Faulty / Sent for Repair'), ('damaged', 'Damaged / Scrap Material')], default='for_repair', max_length=30)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('condition_returned', models.CharField(blank=True, choices=[('repaired', 'Repaired & Fully Working'), ('same', 'Same Condition (Unchanged)'), ('damaged', 'Beyond Repair / Returned Damaged')], max_length=30)),
                ('is_returned', models.BooleanField(default=False)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='gatepass_items/')),
                ('pass_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gatepass.gatepass')),
            ],
        ),
    ]
