# Generated by Django 6.1.1 on 2026-09-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_securitygate_alter_securityauditlog_action_and_more'),
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='core.securitygate'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='gate_location',
            field=models.CharField(default='Loading Dock Gate', max_length=100),
        ),
    ]
