# Generated by Django 6.1.1 on 2026-09-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_alter_securityauditlog_action_and_more'),
        ('gatepass', '0002_gatepass_gate_alter_gatepass_gate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='core.property'),
        ),
    ]
