# Generated by Django 6.1.1 on 2026-09-14 12:13

import django.db.models.deletion
import django.utils.timezone
import visitors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor_room', models.CharField(blank=True, help_text='e.g. Floor 3 / Room 302 / Admin Office', max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(default=visitors.models.generate_pass_number, editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('guest', 'Guest / Personal Visitor'), ('contractor', 'Contractor / Technician / Maintenance'), ('delivery', 'Delivery / Courier / Logistics'), ('official', 'VIP / Government / Official Inspector'), ('interview', 'Interviewee / Job Applicant'), ('other', 'Other')], default='guest', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Contractor or employer company', max_length=150)),
                ('id_type', models.CharField(choices=[('national_id', 'Saudi National ID'), ('iqama', 'Iqama / Resident Permit'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('company_badge', 'Company Contractor Badge')], default='national_id', max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='id_photos/')),
                ('visitor_photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('host_person', models.CharField(blank=True, help_text='Staff name, guest name, or room number being visited', max_length=100)),
                ('purpose', models.CharField(help_text='Reason for entry / visit', max_length=250)),
                ('has_vehicle', models.BooleanField(default=False)),
                ('vehicle_plate', models.CharField(blank=True, help_text='e.g. ABC 1234', max_length=30)),
                ('vehicle_model', models.CharField(blank=True, help_text='e.g. Toyota Hilux, White', max_length=60)),
                ('parking_slot', models.CharField(blank=True, max_length=30)),
                ('tools_declared', models.TextField(blank=True, help_text='Tools, equipment, heavy gear declared at gate')),
                ('gate_location', models.CharField(choices=[('Main Gate', 'Main Security Gate'), ('Staff Entrance', 'Staff & Service Entrance'), ('Loading Dock', 'Loading Dock / Delivery Gate'), ('VIP Lobby', 'VIP / Executive Entrance')], default='Main Gate', max_length=50)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_checkout_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'On Premises (Checked In)'), ('checked_out', 'Checked Out'), ('overstay', 'Flagged Overstay'), ('denied', 'Entry Denied')], default='active', max_length=20)),
                ('badge_returned', models.BooleanField(default=False)),
                ('security_notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_checked_out', to=settings.AUTH_USER_MODEL)),
                ('host_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='visitors.departmenthost')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
