# Generated by Django 6.1.1 on 2026-09-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_alter_securityauditlog_action_and_more'),
        ('visitors', '0002_visitor_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthost',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.property'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='core.property'),
        ),
    ]
